# Generated by Django 5.0.1 on 2024-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
        ('materials', '0004_delete_homeworkmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='documents',
            field=models.ManyToManyField(to='materials.document'),
        ),
    ]
