# Generated by Django 5.0.1 on 2024-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_homework_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.IntegerField(choices=[(0, 'homework'), (1, 'project')], default=0, verbose_name='тип задания'),
        ),
    ]
