# Generated by Django 5.0.1 on 2024-06-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_homework_type'),
        ('materials', '0004_delete_homeworkmaterials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.IntegerField(choices=[(0, 'assigned'), (1, 'done'), (2, 'undone'), (3, 'under_review')], default=0),
        ),
        migrations.CreateModel(
            name='TeacherAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_answers', to='homeworks.answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(to='materials.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
