# Generated by Django 5.0.1 on 2024-06-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_homework_status_teacheranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(0, 'assigned'), (1, 'done'), (2, 'undone'), (3, 'under_review')], default=0),
        ),
    ]
