# Generated by Django 5.0.1 on 2024-07-20 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0007_alter_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
