# Generated by Django 5.0.1 on 2024-06-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_discipline_default_link_alter_discipline_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='default_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('work day', 'Work day'), ('day off', 'Day off')], default='work day', max_length=8)),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='schools.school')),
            ],
        ),
    ]
