# Generated by Django 5.0.1 on 2024-06-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_discipline_default_link_schoolperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolperiod',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.school'),
        ),
    ]
