# Generated by Django 5.0.1 on 2024-06-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schoolperiod_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='last_name_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='wats_app',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
