# Generated by Django 5.0.1 on 2024-06-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_email_school_first_name_school_last_name_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='last_name_name',
            new_name='last_name',
        ),
    ]
