# Generated by Django 5.0.1 on 2024-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_rename_last_name_name_school_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='first_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='last_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='wats_app',
            field=models.TextField(blank=True, default=''),
        ),
    ]
