# Generated by Django 5.0.1 on 2024-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_description_school_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
