# Generated by Django 5.0.1 on 2024-05-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_lessons', to='schools.discipline'),
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='students',
            field=models.ManyToManyField(related_name='master_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.masterlesson'),
        ),
        migrations.AddField(
            model_name='period',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.grade'),
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.period'),
        ),
    ]
