# Generated by Django 5.0.1 on 2024-05-31 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_discipline_default_link_alter_discipline_teacher_and_more'),
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlesson',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_lessons', to='schools.grade'),
        ),
    ]
