# Generated by Django 5.0.1 on 2024-06-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_masterlesson_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlesson',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='masterlesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=50),
        ),
    ]
