# Generated by Django 5.0.1 on 2024-06-16 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_masterlesson_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlesson',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='masterlesson',
            name='end_time',
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='duration',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='masterlesson',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.masterlesson'),
        ),
    ]
