# Generated by Django 5.0.1 on 2024-05-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeworks', '0002_initial'),
        ('materials', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmaterials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homework_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworkmaterials',
            name='documents',
            field=models.ManyToManyField(to='materials.document'),
        ),
        migrations.AddField(
            model_name='homeworkmaterials',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='lessonmaterials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmaterials',
            name='documents',
            field=models.ManyToManyField(to='materials.document'),
        ),
        migrations.AddField(
            model_name='lessonmaterials',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='timetable.lesson'),
        ),
        migrations.AddField(
            model_name='materials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materials',
            name='documents',
            field=models.ManyToManyField(to='materials.document'),
        ),
        migrations.AddField(
            model_name='materials',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
