# Generated by Django 5.0.1 on 2024-05-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_document_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkMaterials',
        ),
    ]
