# Generated by Django 5.0.1 on 2024-07-20 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_delete_homeworkmaterials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='lessonmaterials',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materials',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
