# Generated by Django 5.0.1 on 2024-06-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_password', 'can change password'), ('can_edit_school', 'can edit school'), ('can_view_school', 'can view school'), ('can_delete_school', 'can delete school')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
