# Generated by Django 5.0.1 on 2024-06-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_password', 'can change password'), ('can_edit_school', 'can edit school'), ('can_view_school', 'can view school'), ('can_delete_school', 'can delete school'), ('can_delete_material', 'can_delete_material'), ('can_edit_all_materials', 'can_edit_all_materials'), ('can_edit_all_lesson_materials', 'can_edit_all_lesson_materials'), ('can_delete_lesson_materials', 'can_delete_lesson_materials'), ('can_view_all_users', 'can_view_all_users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
