# Generated by Django 5.0.1 on 2024-07-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_user_timezone_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_password', 'can change password'), ('can_create_school', 'can_create_school'), ('can_edit_school', 'can edit school'), ('can_view_school', 'can view school'), ('can_delete_school', 'can delete school'), ('can_delete_material', 'can_delete_material'), ('can_edit_all_materials', 'can_edit_all_materials'), ('can_edit_all_lesson_materials', 'can_edit_all_lesson_materials'), ('can_delete_lesson_materials', 'can_delete_lesson_materials'), ('can_view_users', 'can_view_users'), ('can_create_users', 'can_create_users'), ('can_edit_users', 'can_edit_users'), ('can_delete_users', 'can_delete_users'), ('can_create_discipline', 'can_create_discipline'), ('can_delete_discipline', 'can_delete_discipline'), ('can_create_classes', 'can_create_classes'), ('can_view_classes', 'can_view_classes'), ('can_delete_classes', 'can_delete_classes'), ('can_edit_timetable_template', 'can_edit_timetable_template'), ('can_edit_student_list', 'can_edit_student_list')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
